version: '3.5'

services:
  express-hello-world:
    build: .
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    container_name: express-hello-world

volumes:
  node_modules:
