name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, push and deploy to Heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "exporess-hello-world"
          email: "oskari.kotajarvi@gmail.com"
          docker_compose_file: './docker-compose-dev.yml'
          heroku_apps: '[{"imagename":"express-hello-world","appname":"express-hello-world","apptype":"web"}]'
